- name: Update_Cache
  apt: update_cache=yes

- name: Install Docker Engine
  apt: name=docker.io state=present

- name: Start Docker Service
  service: name=docker state=started

- name: Permission for user
  user: name={{demouser}} group=docker

- name: Install Docker Compose
  apt: name=docker-compose state=present
